# Generated by Django 6.0.4 on 2026-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('host', 'HOST'), ('driver', 'DRIVER')], default='driver', max_length=20),
        ),
    ]
