# Generated by Django 6.0.4 on 2026-04-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('HOST', 'HOST'), ('DRIVER', 'DRIVER')], default='DRIVER', max_length=20),
        ),
    ]
