# Generated by Django 6.0.4 on 2026-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='has_ev_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='has_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='vehicle_size',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('large', 'Oversized / Truck')], max_length=20),
        ),
    ]
