# Generated by Django 6.0.1 on 2026-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkingspot_has_cctv_parkingspot_has_ev_charging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_reason',
            field=models.CharField(blank=True, help_text='no_show, driver_cancelled, host_cancelled', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
    ]
