# Generated by Django 6.0.1 on 2026-04-30 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_cancelled_reason_booking_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.parkingspot'),
        ),
    ]
