# Generated by Django 6.0.1 on 2026-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parkingspot_is_deleted_alter_booking_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
